# Generated by Django 4.0.4 on 2022-06-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('nrocliente', models.FloatField()),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
