# Generated by Django 4.0.4 on 2022-06-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecliente', models.CharField(max_length=100)),
                ('direccionfiscal', models.CharField(max_length=100)),
                ('cuit', models.IntegerField()),
                ('fechaingreso', models.DateField()),
                ('antiguedad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreapellido', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=100)),
                ('dni', models.IntegerField()),
                ('fechaing', models.DateField()),
                ('antig', models.IntegerField()),
            ],
        ),
    ]
