# Generated by Django 4.0.4 on 2022-06-08 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_clientes_empleados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='fechaingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='fechaing',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
